on:
  issues:
    types:
      - opened

jobs:
  create_pr:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
      ISSUE_NUM: ${{ github.event.issue.number }}
      ISSUE_TITLE: ${{ github.event.issue.title }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      id-token: write
      issues: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup blogsync
        env:
          BLOGSYNC_VER: v0.10.2
        run: |
          brew update
          brew install Songmu/tap/blogsync
          user=$(whoami)
          echo ${user}
          ls -lha /home/linuxbrew/.linuxbrew/bin
          chown -R ${user} /home/linuxbrew/.linuxbrew/bin/blogsync
        
      - name: Create files
        run: |
          mkdir $ISSUE_NUM
          echo -e "blog執筆用のデフォルトファイルを配置" \
            >> $ISSUE_NUM/blog.md

      - name: Define new branch name
        id: define_new_branch_name
        run: |
          new_branch_name=$(echo "blog_${ISSUE_NUM}")
          echo "::set-output name=new_branch_name::$new_branch_name"

      - name: Create branch
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: ${{ steps.define_new_branch_name.outputs.new_branch_name }}

      - name: Create PR
        run: |
          gh pr create \
            --head $NEW_BRANCH_NAME \
            --base $BASE_BRANCH_NAME \
            --title "$ISSUE_TITLE" \
            --body "issue #${ISSUE_NUM}"
        env:
          NEW_BRANCH_NAME: ${{ steps.define_new_branch_name.outputs.new_branch_name }}
          BASE_BRANCH_NAME: ${{ github.event.repository.default_branch }}
          
      - name: post new entry
        run: |
          echo | blogsync post --draft $ISSUE_NUM/blog.md
          
