on:
  pull_request:
    types: synchronize

jobs:
  push_entry:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TZ: 'Asia/Tokyo'
    permissions:
      id-token: write
      issues: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          
      - name: Install dependencies
        run: bundle install
      
      - name: Setup blogsync
        env:
          BLOGSYNC_VER: v0.12.1
        run: |
         mkdir bin
          curl --location --output blogsync.tar.gz --remote-name https://github.com/motemen/blogsync/releases/download/${BLOGSYNC_VER}/blogsync_${BLOGSYNC_VER}_linux_amd64.tar.gz
          tar zxf blogsync.tar.gz -C bin --strip-component 1 blogsync_${BLOGSYNC_VER}_linux_amd64/blogsync

      - name: append blogsync path to PATH
        run: echo "./bin" >> $GITHUB_PATH
        
      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v31
                   
      - name: push entry
        run: |
          draft_file=$(echo "${{ steps.changed_files.outputs.all_changed_files }}" | grep -Eo "\S+\.md" | cat)
          image_file_path=$(dirname $draft_file)
          ruby scripts/post_image.rb --imagedir $image_file_path --filename $draft_file
          bin/blogsync push $draft_file
        env:
          BLOGSYNC_USERNAME: ${{ secrets.USERNAME }}
          BLOGSYNC_PASSWORD: ${{ secrets.PASSWORD }}
          HATENABLOG_CONSUMER_KEY: ${{ secrets.HATENABLOG_CONSUMER_KEY }}
          HATENABLOG_CONSUMER_SECRET: ${{ secrets.HATENABLOG_CONSUMER_SECRET }}
          HATENABLOG_ACCESS_TOKEN: ${{ secrets.HATENABLOG_ACCESS_TOKEN }}
          HATENABLOG_ACCESS_TOKEN_SECRET: ${{ secrets.HATENABLOG_ACCESS_TOKEN_SECRET }}
          
          
          
