on:
  pull_request:
    types: synchronize

jobs:
  push_entry:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TZ: 'Asia/Tokyo'
    permissions:
      id-token: write
      issues: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git checkout ${{ github.head_ref }}
      
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          
      - name: Install dependencies
        run: bundle install
      
      - name: Setup blogsync
        env:
          BLOGSYNC_VER: v0.12.1
        run: |
         mkdir bin
          curl --location --output blogsync.tar.gz --remote-name https://github.com/motemen/blogsync/releases/download/${BLOGSYNC_VER}/blogsync_${BLOGSYNC_VER}_linux_amd64.tar.gz
          tar zxf blogsync.tar.gz -C bin --strip-component 1 blogsync_${BLOGSYNC_VER}_linux_amd64/blogsync

      - name: append blogsync path to PATH
        run: echo "./bin" >> $GITHUB_PATH
        
      - name: Get changed files
        id: changed_files
        uses: technote-space/get-diff-action@v6
                   
      - name: push entry
        id: push_entry
        run: |
          draft_file=$(echo "${{ env.GIT_DIFF }}" | grep -Eo "'(\S+\.md)'" | cat)
          blog_path=$(dirname $draft_file)
          ruby scripts/post_image.rb --blogdir "$blog_path" --filename $draft_file
          bin/blogsync push $draft_file
          cat $draft_file
          echo "::set-output name=blog_path::$blog_path"
        env:
          BLOGSYNC_USERNAME: ${{ secrets.USERNAME }}
          BLOGSYNC_PASSWORD: ${{ secrets.PASSWORD }}
          HATENABLOG_CONSUMER_KEY: ${{ secrets.HATENABLOG_CONSUMER_KEY }}
          HATENABLOG_CONSUMER_SECRET: ${{ secrets.HATENABLOG_CONSUMER_SECRET }}
          HATENABLOG_ACCESS_TOKEN: ${{ secrets.HATENABLOG_ACCESS_TOKEN }}
          HATENABLOG_ACCESS_TOKEN_SECRET: ${{ secrets.HATENABLOG_ACCESS_TOKEN_SECRET }}

      - name: image json push
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git pull
          git add "${{ steps.push_entry.outputs.blog_path }}/image.json"
          change_image_json=$(git status -s | grep -Eo "M\s\s.+/image\.json" | cat)
          echo $change_image_json
          if [ -n "$change_image_json" ] ; then
            echo "commit"
            git commit -m "image.jsonを更新"
            git push origin HEAD:${{ github.head_ref }}
          fi
